### ISSUE TITLE
Can we make the error detail for textfields dynamic ?

### ISSUE THREAD

**Issue by swift1022** [CosmicMind/Material#1017]
When the user is typing email : If the email  is not in Regex format then it should the error ("invalid") automatically and when the email is again edited  in Regex format then the error must be removed automatically while editing. Is it possible to do using this library ?? 
 Just like as shown in  screenshots below for Email field :

![simulator screen shot - iphone 8 - 2018-01-10 at 21 48 20](https://user-images.githubusercontent.com/25656422/34782259-45c00e98-f650-11e7-8873-f4e656b79b56.png)
![simulator screen shot - iphone 8 - 2018-01-10 at 21 49 22](https://user-images.githubusercontent.com/25656422/34782260-475a3a44-f650-11e7-98a6-91af5a8a585d.png)

**Comment by danieldahan** [comment]
You can do this using the delegation methods associated with the TextField. There is not a validation check for the values added, at least not at the moment. It would be a good feature though, and has been noted prior. I will add a feature request tag to this and make a sample or build it into Material. Thank you!

**Comment by adamdahan** [comment]
@danieldahan @Maddy10 Validation should live outside of the framework as there are too many types of fields and validations. Ideally you would have a protocol to enable such functionality. 

`protocol TextFieldValidator { 
     func validatateTextField() 
 }

protocol EmailTextFieldValidator: TextFieldValidator {}
protocol PhoneTextFieldValidator: TextFieldValidator {}

Then you can conform to your protocol when you need to validate a specific field and implement the validateTextField signature. 

Let me know if this makes sense - otherwise I can make a sample. 

Best!
`

**Comment by danieldahan** [comment]
I agree @adamdahan. Are you suggesting to leave this outside of Material for now?

**Comment by OrkhanAlikhanov** [comment]
Made PR for this #1082

**Comment by OrkhanAlikhanov** [comment]
#1082 is merged in, so next release gonna have this feature.  For the usage guide see the PR description. Thank you!

**Comment by danieldahan** [comment]
I am going to close this issue as the PR is merged in. Let's focus on tomorrow making a release.
