### ISSUE TITLE
Combining navigation drawer with back navigation 

### ISSUE THREAD

**Issue by L3K0V** [CosmicMind/Material#1033]
I have a drawer where some items must push to navigation instead of replacing the main content and change the drawer to back navigation, so my question is possible to combine `NavigationDrawerController` with `NavigationController`.

I tried to chain the controllers but I get two toolbars

```
let appToolbarController = AppToolbarController(rootViewController: RootViewController())
let navigationController = NavigationController(rootViewController: appToolbarController)

self.window = application.windows.first ?? UIWindow(frame: Screen.bounds)
self.window = UIWindow(frame: Screen.bounds)
self.window!.rootViewController = AppNavigationDrawerController(rootViewController: navigationController, leftViewController: viewController)
self.window!.makeKeyAndVisible()
```

`AppToolbarController` extends `ToolbarController` as the example project using drawer

**Comment by danieldahan** [comment]
Sorry this response took a while. You are getting two toolbars because you are using the `ToolbarController` and `NavigationController`. You only need one. If you use the `NavigationController` it will manage a `back button` for you, otherwise, you will need to do it manually with a `ToolbarController`. 

If you need any further help, please reopen this issue. Thank you!
