### ISSUE TITLE
Can't access TransitionController

### ISSUE THREAD

**Issue by Recouse** [CosmicMind/Material#1050]
`TransitionController` is internal to the framework, so it can't be subclassed.

**Comment by OrkhanAlikhanov** [comment]
Hey, I can confirm that it's not internal and never been. So it can be subclassed.
https://github.com/CosmicMind/Material/blob/dd741ff01a13be2bb45d47b256290be42511f361/Sources/iOS/TransitionController.swift#L34

Actually it can never be internal because other open classes like `TabsController` inherits from it and you cannot give higher access level in subclasses to the types that have lower access level (at least in swift).

**Comment by danieldahan** [comment]
Excellent, let's close this. Thank you!
