### ISSUE TITLE
TextField isErrorRevealed error

### ISSUE THREAD

**Issue by moazkh60** [CosmicMind/Material#1131]
I updated my Material library and now the textField error is now revealed by default and when I try textField.isErrorRevealed = true it get's invisible it was working fine before and now the situation is reverted.

**Comment by OrkhanAlikhanov** [comment]
@moazkh60 Hey, thank you for reporting this! `ErrorTextField` has changed a bit by #1082. Now, instead of showing error in `detailLabel` we show it in new `errorLabel`. So setting `isErrorRevealed = true` hides `detailLabel` and shows `errorLabel`. Update your code to use `errorLabel` and `error: String?` instead of `detailLabel` and `detail: String?`

**Comment by danieldahan** [comment]
@OrkhanAlikhanov thank you for the explanation.

**Comment by phlippieb** [comment]
Ah, that explains it 🙁
