### ISSUE TITLE
Hiding TabBar of TabsController 

### ISSUE THREAD

**Issue by Hamna21** [CosmicMind/Material#1136]
Hello,

I am using TabsConstroller having four view controllers. The root controller of each is a navigation controller.

The flow is TabsContoller -> NavigationController -> View Controller. 

How can I hide tab bar in any of the view controllers?

I tried **tabBar.isHidden** = true but that left a blank space and **hidesBottomBarWhenPushed** didn't work with material tabBar.

Is there a material function available for hiding tabBar?

**Comment by OrkhanAlikhanov** [comment]
Hey! Thank your sharing your issues with us!

`hidesBottomBarWhenPushed ` is only for `BottomNavigationController` (which is subclass of `UITabBarController`). `TabsController` does not support it, but yeah, we should add that option I think.

Instead of `tabBar.isHidden = true`, do `displayStyle = .full`

**Comment by Hamna21** [comment]
@OrkhanAlikhanov Thank you for replying and the new information! 

Can you tell me the difference between `TabsController` and `BottomNavigationController`? and what is the added functionality or advantage of using BottomNavigationController.

By using BottomNavigationController, do I still have to insert a navigation controller for a viewController or is that default?
I want my flow to be like this: TabsContoller -> NavigationController -> View Controller.
