### ISSUE TITLE
AppTabsController not showing tabs (Top alignment) when uses into navigation controller

### ISSUE THREAD

**Issue by shroff-kandarp** [CosmicMind/Material#1148]

**Comment by OrkhanAlikhanov** [comment]
Hey! Can you share a minimal sample project replicating the issue?

**Comment by shroff-kandarp** [comment]
Please follow this link:
https://drive.google.com/file/d/18bWFlCXARqwxppO_dL7gBBUepijUAV_j/view?usp=sharing

**Comment by OrkhanAlikhanov** [comment]
@shroff-kandarp You are using `UINavigationController`, that's how it behaves when `navigationBar.isTranslucent` is `true` (default is true). It extends the `rootViewController`. You can set `navigationController.navigationBar.isTranslucent = false` or in your controller `self.edgesForExtendedLayout = []` to prevent extending. And also, we recommend using `NavigationController` instead of `UINavigationController`.

That said, @danieldahan what do you think, should we default `edgesForExtendedLayout = []` for `TabsController` perhaps when alignment is `.top`?

**Comment by danieldahan** [comment]
@OrkhanAlikhanov That is a great idea. Please and thank you.

**Comment by OrkhanAlikhanov** [comment]
@shroff-kandarp We decided that we keep it as it is, since it's default behavior of the system when using `UINavigationController`. That said, you should use Material's `NavigationController` instead of `UINavigationController`.

**Comment by danieldahan** [comment]
@OrkhanAlikhanov Thank you for following up. @shroff-kandarp If you have any further questions or issues, please reopen or create a new one. Thank you!
