### ISSUE TITLE
left view padding is not working properly in swift 4

### ISSUE THREAD

**Issue by Madhav1022** [CosmicMind/Material#1164]
When I add left view for padding in textfieldd, the text in the textfield goes to middle of textfield. Although I give only 1 units for width of left view. Please help me to sort out this issue ? Code is given below: 

    func fullNameField() {
    self.fullnameField.placeholder = "Full Name*"
    self.fullnameField.backgroundColor = UIColor.white
    self.fullnameField.delegate = self
    self.fullnameField.textColor = UIColor.lightGray
    self.fullnameField.isPlaceholderUppercasedWhenEditing = false
    self.fullnameField.placeholderAnimation = .default
    self.fullnameField.placeholderNormalColor = UIColor.lightGray
    self.fullnameField.placeholderActiveColor =  UIColor.black
    self.fullnameField.placeholderVerticalOffset = 15
    self.fullnameField.leftView = UIView(frame: CGRect(x: 0, y: 0, width: 1, height: 
    self.fullnameField.frame.height))
    self.fullnameField.leftViewMode = .always
    }

**Comment by OrkhanAlikhanov** [comment]
That's because we calculate width of `leftView` differently `leftViewOffset + bounds.height`:
https://github.com/CosmicMind/Material/blob/6dc1048c419d5ed5989852605518b6e3be6ea5db/Sources/iOS/TextField.swift#L106-L116

You can override our calculation to give 10 points left padding as follows:
```swift
class myTextField: TextField {
    override func layoutSubviews() {
        super.layoutSubviews()
        
        leftViewOffset = -bounds.height + 10
    }
}

let fullnameField = myTextField()
fullnameField.placeholder = "Full Name*"
fullnameField.backgroundColor = UIColor.white
fullnameField.leftView = UIView()
```
This padding will also be reflected on divider line.


---
If you don't want divider line to be padded you can just inset the text using `textInsets` property which is available in `development` branch right now.

```swift
let fullnameField = TextField()
fullnameField.placeholder = "Full Name*"
fullnameField.backgroundColor = UIColor.white
fullnameField.textInsets.left = 50
```

**Comment by OrkhanAlikhanov** [comment]
@danieldahan What do you think in this matter?

**Comment by danieldahan** [comment]
@Madhav1022 what branch/version are you using for this, and can you send me an image of what is happening now, and what it looked like before please?

**Comment by danieldahan** [comment]
@Madhav1022  If you still face this issue, please reopen this. Thank you!
