### ISSUE TITLE
RTL UITextField

### ISSUE THREAD

**Issue by pedroOliveiraptc** [CosmicMind/Material#1166]
Hey guys congrats for the work.
i am facing a problem since ios12 and the new version that you guys release, my textfield in rtl break alignments as you can see above,

<img width="318" alt="captura de ecra 2018-10-02 as 13 11 03" src="https://user-images.githubusercontent.com/12796621/46347870-f5e06600-c644-11e8-805d-fded1d03ea79.png">

<img width="296" alt="captura de ecra 2018-10-02 as 13 11 10" src="https://user-images.githubusercontent.com/12796621/46347877-fb3db080-c644-11e8-9182-744a182aefa2.png">

<img width="297" alt="captura de ecra 2018-10-02 as 13 11 17" src="https://user-images.githubusercontent.com/12796621/46347882-fed13780-c644-11e8-9eff-e47b7b6ff19c.png">

<img width="296" alt="captura de ecra 2018-10-02 as 13 11 24" src="https://user-images.githubusercontent.com/12796621/46347891-01339180-c645-11e8-9902-f364d69aa644.png">

Do you already face this issue ? On iOS 11 and old version of the framework I don't have problems.
Thanks.

**Comment by danieldahan** [comment]
Hey @pedroOliveiraptc,  Thank you. Can you try the `development` branch, and let us know if the issue persists. If so, please send a reproducible issue so we can investigate it. Thank you!

**Comment by pedroOliveiraptc** [comment]
@danieldahan thanks I will try.

**Comment by pedroOliveiraptc** [comment]
> Hey @pedroOliveiraptc, Thank you. Can you try the `development` branch, and let us know if the issue persists. If so, please send a reproducible issue so we can investigate it. Thank you!

Hello the placeholder its ok, but the input text and the component line it self are not aligned. 
<img width="312" alt="captura de ecra 2018-10-03 as 08 57 55" src="https://user-images.githubusercontent.com/12796621/46397628-950b6900-c6ea-11e8-92e1-bbde10c3e403.png">

**Comment by OrkhanAlikhanov** [comment]
@pedroOliveiraptc Can you share the code for us to achieve the same result on our computer?

**Comment by pedroOliveiraptc** [comment]
> @pedroOliveiraptc Can you share the code for us to achieve the same result on our computer?

i will create a sample app to share.
thanks.

**Comment by danieldahan** [comment]
@pedroOliveiraptc Are you still facing this issue? If so, please reopen this and submit a sample app. Thank you!

**Comment by pedroOliveiraptc** [comment]
Hello sorry for the delay, the link for sample project

https://drive.google.com/file/d/1gl4BQvgH2QvU5FrU0FM3ViHDwUVVr_7U/view

**Comment by OrkhanAlikhanov** [comment]
Thank you we'll look into soon.

**Comment by OrkhanAlikhanov** [comment]
@pedroOliveiraptc You have following line:
```swift
UIView.appearance().semanticContentAttribute = .forceRightToLeft
```
It makes some changes internal to `UITextField`: 
![image](https://user-images.githubusercontent.com/15037839/47244632-40186400-d407-11e8-8f4b-8dc47cfcc387.png)
From: [#WWDC15 App Frameworks](https://devstreaming-cdn.apple.com/videos/wwdc/2015/222ngkqh58b52/222/222_new_uikit_support_for_international_user_interfaces.pdf)

We give padding as much as the height of the `textField` if `leftView` has non-nil value. Since `leftView` is swapped with `rightView` internally when you have `.forceRightToLeft`, accessing leftView returns non-nil value (value of rightView) therefore we add padding. You workaround this by setting `rightView` to nil:
```swift
let textField = TextField()
textField.rightView = nil // so that when it gets swapped with leftView, leftView still stays nil
```
Actually we don' support RTL yet, so we don't test our framework against such cases.


btw, you can use `development` branch, it has cool updates such as Theming (#1115) and Dialog (#1173) :)

**Comment by danieldahan** [comment]
@OrkhanAlikhanov I created an issue for us to support RTL. https://github.com/CosmicMind/Material/issues/1179, let's follow that issue for the RTL feature.
