### ISSUE TITLE
Feature Request - TextField DropDown Suggestion

### ISSUE THREAD

**Issue by SDGMazeGeek** [CosmicMind/Material#1196]
Can there be anything like this? Assigning an array will show a dropdown/tableView under/over the textfield when it's focused. Selecting item will replace the text.

**Comment by danieldahan** [comment]
@SDGMazeGeek You can easily make it, based on your description, we would most likely demonstrate how to build such a component, rather than provide it out of the box. If you would like to start putting together a component like that and want our help, we would be happy to discuss it with you in our Slack channel. You can be invited by sending your email to support@cosmicmind.com. As of now, we don't have the bandwidth to make it completely on our own. Thank you for sharing your idea, it is a really good one.
