### ISSUE TITLE
Several methods in NavigationDrawerController not visible in Objective-C

### ISSUE THREAD

**Issue by emauro** [CosmicMind/Material#1247]
Most methods in NavigationDrawerController are not visible from Objective-C. Example:
setLeftViewWidth, toogleLeftView,  openLeftView, closeLeftView. Same for right counterparts. An @objc is necessary in front of all methods.

**Comment by OrkhanAlikhanov** [comment]
Hey! It has been 5 years that swift is available. I think we don't support objective c anymore in favor of new features of swift which are not available in obj c

**Comment by danieldahan** [comment]
@OrkhanAlikhanov yes that is correct, Swift has been out for a while, but that said, there are still projects out there that need Obj-C support by design.... not necessarily because of desire. If it is as simple as adding `@objc` to the declaration, I don't see adding it would be an issue. If it is a feature solely in Swift, well then we can't do anything about that. Thoughts?

**Comment by emauro** [comment]
>  there are still projects out there that need Obj-C support by design.... not necessarily because of desire

That's the point. I just added @objc and it solved my problem.

**Comment by danieldahan** [comment]
@OrkhanAlikhanov I would say that going forward, our protocol will be to make what can be available easily in Obj-C ~ available.... otherwise, let's move forward with Swift. 

@emauro a PR that would help solve this issue so easily is greatly appreciated, rather than us chasing these methods down.

**Comment by OrkhanAlikhanov** [comment]
Agreed that adding `@objc` won't create any issue for us.

> there are still projects out there that need Obj-C support by design.... not necessarily by desire

That's right. But, it's possible to [use objc code in swift](https://developer.apple.com/documentation/swift/imported_c_and_objective-c_apis/importing_objective-c_into_swift). The guideline I'd set is that if some part of app requires obj-c then do it in obj-c then call that api through swift.

Having said that, in general, supporting obj-c would be burden rather than gain. I'd argue that 1% of our users would call our apis through obj-c, and we may need to sacrifice many nice swift-only features such as generics better enums, etc in order to support obj-c fully.

**Comment by danieldahan** [comment]
@emauro a PR with updates to fix your issue will be available later today, or latest tomorrow. Can you list the methods you found needing to contain the @Objc methods in the declaration, it will help to ensure we don't miss any. Thank you!

**Comment by OrkhanAlikhanov** [comment]
I made a quick PR #1248 adding `@objc`s. @emauro, please check if it meets the requirement :)

**Comment by emauro** [comment]
Thanks! I already checked and posted a comment.

**Comment by danieldahan** [comment]
Please find your fix in this release [Material 3.1.5](https://github.com/CosmicMind/Material/releases/tag/3.1.5)
