### ISSUE TITLE
single SideNavigationController for multiple ViewController

### ISSUE THREAD

**Issue by omidkh68** [CosmicMind/Material#127]

**Comment by danieldahan** [comment]
Hey, 

Do you mean that you want to switch between different ViewControllers within your application, and not have to change the SideNavigationViewController?

If that is the case, you will want to use this method: transitionFromMainViewController.

It provides the ability to swap the SideNav mainViewController with other UIViewControllers. 

Generally, this question is better suited for Stack Overflow. I encourage you to ask the question there so that others may benefit from the response. You are welcome to send a link to the question if you want us to answer it directly.

**Comment by danieldahan** [comment]
I am closing this issue. If you have an issue, please reopen the ticket, or create a new one. Or ask the question on Stack Overflow and send us a link to answer.

**Comment by chaitanya-ramji** [comment]
In fact even I'm facing a similar issue. Could you add transitioning between view controllers in the sample code in your next update? It would really help us.

**Comment by danieldahan** [comment]
Hey, you may be looking for this method, transitionFromMainViewController.

It allows you to switch the mainViewController with animation and transition options. 

I will add an example of using this feature in my next update.

**Comment by vamseems** [comment]
Is there an example added for this?

**Comment by chaitanya-ramji** [comment]
@vamseems It was added as a test app. In case you want to navigate try this: 

```swift
let storyboard = UIStoryboard(name: "Main", bundle: nil)

let VC2 = storyboard.instantiateViewControllerWithIdentifier("ViewController2") as! ViewController2

sideNavigationViewController?.transitionFromMainViewController(VC2, duration: 0.4, options: .CurveEaseIn, animations: nil, completion: { (Bool) -> Void in
                self.sideNavigationViewController?.closeLeftView()
            })
```

**Comment by vamseems** [comment]
@chaitanya-ramji thanks

**Comment by chaitanya-ramji** [comment]
Anytime :)

**Comment by xaviermawet** [comment]
@chaitanya-ramji I tried something similar but it doesn't work. I've updated the AppLeftViewController.swift file of the "App" project in Examples. To make tests, I wanted to replace the BottomNavigationController by the PhotoViewController if the first row in the table menu is selected, otherwise by the VideoViewController : 
``` 
/// UITableViewDelegate methods.
extension AppLeftViewController: UITableViewDelegate {
	/// Sets the tableView cell height.
	func tableView(tableView: UITableView, heightForRowAtIndexPath indexPath: NSIndexPath) -> CGFloat {
		return 64
	}

	/// Select item at row in tableView.
	func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath) {

        let newVC = (indexPath.row == 0) ? PhotoViewController() : VideoViewController()

        sideNavigationController?.transitionFromRootViewController(newVC, duration: 0.4, options: .CurveEaseIn, animations: nil, completion: { (Bool) -> Void in
            self.sideNavigationController?.closeLeftView()
        })
	}
}
```

But 

1. The left view never closed. I had to close it before the transitionFromRootViewController
2. We lose the pan and tap gestures. Enable to close the left menu with tap or pan gesture

Could you help me to solve this issue ? 
Thanks a lot (and sorry for my english)  👍

**Comment by danieldahan** [comment]
There is a breakage here.

**Comment by danieldahan** [comment]
I am looking into it.

**Comment by danieldahan** [comment]
@xaviermawet @chaitanya-ramji 

So the issue is, the RecipesViewController has a line of code in the ```viewWillDisappear``` method that disables the ```sideNavigationController```

```swift
sideNavigationController?.enabled = false
```

That line should actually go into the ItemViewController's ```viewWillAppear``` method. Once that change is made, you will find that this line of code in the AppLeftViewController works as expected. 

```swift
func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath) {
		sideNavigationController?.transitionFromRootViewController(VideoViewController(), duration: 0.4, options: .CurveEaseIn, animations: nil, completion: { [unowned self] _ in
			self.sideNavigationController?.closeLeftView()
		})
	}
```

That should work for you :)
