### ISSUE TITLE
Programatically pulse the card view

### ISSUE THREAD

**Issue by JoeShi** [CosmicMind/Material#144]
I use the CardView to let user to choose options. What I am expecting is if the user touches on the container view, the cardView can pulse. Thus the user can get a intuitive response that they should choose options before performing other operations. 

I am looking for some function like `cardView.pulse()`. BTW, I don't too much about UI, can we use pulse to lead the user to follow our workflow.

<img width="399" alt="screen shot 2016-02-04 at 6 23 17 pm" src="https://cloud.githubusercontent.com/assets/2173635/12812342/b125b8a6-cb6c-11e5-9b19-fc43f242d4a4.png">

**Comment by danieldahan** [comment]
Hi @JoeShi,

I like your idea. I will provide functionality to trigger the pulse programmatically.

**Comment by danieldahan** [comment]
Hey @JoeShi, 

We added the programmatic pulse trigger for you. It Optionally takes in a point within the view to trigger the pulse animation from, otherwise defaults to the center. 

An example may be found here: https://github.com/CosmicMind/Material/wiki/MaterialPulseView

If you have any further questions, please reopen this ticket, use StackOverflow, or create a new issue.
