### ISSUE TITLE
Add tableView to CardView?

### ISSUE THREAD

**Issue by eeschimosu** [CosmicMind/Material#152]
Is it possible to add a UITableView inside a CardView?

**Comment by danieldahan** [comment]
It is possible to add a UITableView to a CardView, though, it may be awkward to work with it. What kind of layout are you trying to achieve? I will recommend an approach.

**Comment by eeschimosu** [comment]
I want to make a list with UISwitches in it, and I thought the table with be appropriate for this.

**Comment by danieldahan** [comment]
What parts of the CardView are you planning to display, title? detail? etc... the reason I ask, is because if you want an overlay, like the CardView with a tableView in it. You can easily accomplish that with a MaterialView, or MaterialPulseView, and set the depth property to the appropriate depth. If you are looking to have buttons and all the features CardView provides, then you can add the tableView as a child of the cardView and use the insets to space everything correctly. If you further explain the layout you are looking to achieve, I will provide you some code to get you going.

**Comment by eeschimosu** [comment]
hey daniel! Thanks for your interest!

The layout I'm looking to achieve is something like this.

CardView Title | 
------------ | 
'Text in cell 1'  + ```UISwitch``` |
'Text in cell 2'  + ```UISwitch``` |
'Text in cell 3'  + ```UISwitch``` |
'Text in cell 4'  + ```UISwitch``` |
'Text in cell 5'  + ```UISwitch``` |
'Text in cell 6'  + ```UISwitch``` |
  ```FlatButton``` |

**Comment by danieldahan** [comment]
I am going to release an update to the CardView that will allow you to use this option, and really any option of any view in the detail area. The example project will use a UITableView as one of the examples. Give me about an hour.

**Comment by danieldahan** [comment]
Thanks for the challenge :) Now CardView and ImageCardView support a property called detailView that allows any view to be in the detail area. There is an example project, Examples/Programmatic/CardView/TableCardView that shows how to achieve what you are looking for :)

**Comment by eeschimosu** [comment]
@danieldahan: Thanks very much! You're such an awesome person! You made my day! Cheers!
