### ISSUE TITLE
TextField titleLabel and detailTextLabel size is calculated incorrectly

### ISSUE THREAD

**Issue by DenHeadless** [CosmicMind/Material#157]
Hi!

I encountered problem with TextField, where titleLabel and detailLabel get chopped with specific letters. This is easily reproducible in example project, if you try to show low spaced letters like "g j y" in titleLabel. 

For example, changing email placeholder to 
```swift
nameField.placeholder = "First g j y Name"
```
yields in this result:

http://d.pr/i/1iUKa

Maybe i'm missing something and there's easy way to fix this?

Thanks in advance.

**Comment by danieldahan** [comment]
Hey, sorry about that. The math was using points and didn't take the screen scale into account. I had made a fix for it. This will be released in the next release, which is pushed to tomorrow, rather than today. If you would like to correct it, the best thing would be to grab the development file [TextField](https://github.com/CosmicMind/Material/blob/development/Sources/TextField.swift) for this [Commit](https://github.com/CosmicMind/Material/commit/5f151b22d2612d1a596a21223c7861e4caa2675e). Look in the or in the dev

**Comment by danieldahan** [comment]
I am closing this ticket. The fix is in the next release. Thanks again :)

**Comment by DenHeadless** [comment]
No problem, thanks for an awesome framework!
