### ISSUE TITLE
Shadow Implementation Causes Major Frame Rate Performance Hit

### ISSUE THREAD

**Issue by zgosalvez** [CosmicMind/Material#186]
Hello. Great job on doing these components. 😀

I'm using CardView for my collection view cells and the shadow is causing the the frame rate to go really down when scrolling / animating / pulsing. I traced the source to https://github.com/CosmicMind/Material/blob/master/Sources/MaterialView.swift and it appears that you're using an unideal implementation of shadow.

I've seen suggestions online to fix this like: http://stackoverflow.com/questions/9997972/calayer-shadow-causes-a-performance-hit

Let me know what you think, or when we can expect a fix.

Thanks.

**Comment by misbell** [comment]
Shadows are usually performance intensive.

"Specify a Shadow Path When Adding a Shadow to Your Layer
Letting Core Animation determine the shape of a shadow can be expensive and impact your app’s performance. Rather than letting Core Animation determine the shape of the shadow, specify the shadow shape explicitly using the shadowPath property of CALayer. When you specify a path object for this property, Core Animation uses that shape to draw and cache the shadow effect. For layers whose shape never changes or rarely changes, this greatly improves performance by reducing the amount of rendering done by Core Animation."

https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/CoreAnimation_guide/ImprovingAnimationPerformance/ImprovingAnimationPerformance.html

**Comment by misbell** [comment]
Just in general I am ABSOLUTELY BLOWN AWAY by this project. The UI is beautiful--and thanks of course to the Material folks, but also hats off to the team that's done this in a language that isn't even finished yet :-)

**Comment by danieldahan** [comment]
Thank you! I am already making the fix for shadows. It will be out later today. @misbell The community around this project is incredible, that is what makes it happen.

**Comment by misbell** [comment]
I am rubbing my hands together thinking about the apps I'm a-gonna make
with this.

On Sat, Feb 27, 2016 at 10:11 AM, Daniel Dahan <notifications@github.com>
wrote:

> Thank you! I am already making the fix for shadows. It will be out later
> today. @misbell <https://github.com/misbell> The community around this
> project is incredible, that is what makes it happen.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CosmicMind/Material/issues/186#issuecomment-189660017>
> .
>



-- 
Mike Isbell

**Comment by mohpor** [comment]
You're not alone Mike, we all do.

**Comment by danieldahan** [comment]
This should be fixed now in [1.34.7](https://github.com/CosmicMind/Material/releases/tag/1.34.7). Thanks for this.

**Comment by zgosalvez** [comment]
@danieldahan Dude, you're fast! And now, so is my app. Cheers!
