### ISSUE TITLE
Missing instructions for MaterialTableViewCell

### ISSUE THREAD

**Issue by transat** [CosmicMind/Material#188]
Hi. Thanks for all your work. Would it be possible to add instructions on how to include the tableview in a project? Cheers.

**Comment by danieldahan** [comment]
Hi @transat 

When making a UITableView with Material, the only difference is using a MaterialTableViewCell rather than a UITableViewCell. Here is a complete example in [code](https://github.com/CosmicMind/Material/blob/master/Examples/Programmatic/App/App/InboxViewController.swift), which is taken from the example [App](https://github.com/CosmicMind/Material/tree/master/Examples/Programmatic/App) project. If you need any further help, please reopen this issue or create a new one. Thank you!

**Comment by transat** [comment]
Thanks. I'm new to Swift. I'm using SBGestureTableView and was trying to make that a subclass of MaterialTableView. I'll have a look at the code from the App project and should be able to figure it out.

Cheers
