### ISSUE TITLE
please make public leftViewThreshold / rightViewThreshold

### ISSUE THREAD

**Issue by hvbnet** [CosmicMind/Material#220]
Hi

could you please make public  leftViewThreshold / rightViewThreshold ?
I need it for map viewer app! anyhow it more customizable.

public var rightViewThreshold: CGFloat = 0

thanks

**Comment by danieldahan** [comment]
Yes, that is not a problem.

**Comment by danieldahan** [comment]
This is now fixed in 1.37.0, which I am preparing for release. The properties are Optional, and called: `leftThreshold` and `rightThreshold`. Note, that in order for them to work correctly, the width of the panels would need to be greater than the threshold, otherwise, they will always close. All the best :)
