### ISSUE TITLE
NavigationController in Storyboard

### ISSUE THREAD

**Issue by zgosalvez** [CosmicMind/Material#230]
Took a while for me to find out that subclassing `NavigationController` then using it in the storyboard does not work properly, i.e. the `navigationBar` and `navigationItems` is not set and configurable.

What's the probable cause for this and will storyboards be supported eventually?

**Comment by danieldahan** [comment]
I have added @IBInspectable and @IBDesignable where appropriate for the next release. The other reason that this is not working, because you are using the leftBarButtonItems and rightBarButtonItems. The Material NavigationController does not use this. They use leftControls and rightControls that build the rightBarButtonItems for you. I will look into supporting the storyboard properties while I make the changes I am making on NavigationBar now.

**Comment by danieldahan** [comment]
In 1.37.0 you should be able to use the updates, which I am preparing for release now.
