### ISSUE TITLE
NavigationBar not visible when using nc.setViewControllers

### ISSUE THREAD

**Issue by HarrisonJackson** [CosmicMind/Material#265]
# Actual Behavior

Resetting the root viewcontroller with `nc.setViewControllers([ViewController()], animated: true)` shows no navigation bar

```
if let wind = self.window {
  let nc = NavigationController(rootViewController: UIViewController())
  nc.setViewControllers([TestViewController()], animated: true)
  wind.rootViewController = nc
}
```
![](https://zapier.cachefly.net/storage/photos/425d8cef2301fab9f82364e109a6d704.png)

vs

```
if let wind = self.window {
  let nc = NavigationController(rootViewController: TestViewController())
 // nc.setViewControllers([TestViewController()], animated: true)
  wind.rootViewController = nc
}
```

![](https://zapier.cachefly.net/storage/photos/dec360d79d41dc36df6901e628639b6b.png)

# Expected behavior

Resetting the root viewcontroller with `nc.setViewControllers([ViewController()], animated: true)` should display the NavigationBar as expected

# Theories

I suspect it has something to do with the way this https://github.com/CosmicMind/Material/blob/master/Sources/NavigationController.swift#L110-L124

This is not getting called with the setVCs method.

**Comment by danieldahan** [comment]
I will take a look at this, thank you! :)

**Comment by HarrisonJackson** [comment]
Much appreciated! Great work on the framework thus far - glad to see this repo is super active.

**Comment by danieldahan** [comment]
So it looks like the solution to your issue, you need to remove the animated: true value to animated: false. I looked all over the internet and found that the issue was a bug, and then not, and then was. If you remove the animation, all is good. I suspect this has to do with triggering the transition mechanism, and when animated is false, it sets the controller and moves along. Can you verify this and then close the issue? 

Thank you!

**Comment by danieldahan** [comment]
I am closing this issue as it has been resolved. Please reopen or create a new issue if this persists. All the best :)
