### ISSUE TITLE
SideNavigationControllerDelegate Not Working

### ISSUE THREAD

**Issue by GreyEcologist** [CosmicMind/Material#266]
Hey, there was a change introduced in the last 7 days that prevents the force unwrapping of the SideNavigationController delegate. Inside my rootViewController, I had to replace the code below:

```
self.sideNavigationController!.delegate = self
```

by: 

```
self.sideNavigationController?.delegate = self
```

The problem is that the delegate methods don't get called anymore. I can look tomorrow morning for the exact build that created the issue. 

Also, I searched for one but didn't find any example that used the SideNavigationControllerDelegate, so if there's an alternative way to set it up than forced unwrapping, please let me know.

**Comment by danieldahan** [comment]
I don't recall anytime that there was a force unwrap. In general, setting up the delegate, requires that you do so when the relationship of the ViewControllers are set. What I mean is, if you create a ViewController, ```MyViewController()``` then set it to the ```SideNavigationController```, the ```sideNavigationController``` Optional is not available in the viewDidLoad. That is because the viewDidLoad before the relationship was met. It should be setup in the ```viewWillAppear``` method. Do you mind sharing your setup code?

**Comment by GreyEcologist** [comment]
Oh nice! That worked! I did have it my my viewDidLoad()

Thanks a lot Dan!
