### ISSUE TITLE
Depth Does Not Change on Pulse

### ISSUE THREAD

**Issue by zgosalvez** [CosmicMind/Material#268]
When a view pulses (and scale), the shadow remains the same and does not present a change of depth. Scale I presume is there to simulate the view getting closer to the fingertip.

**Comment by danieldahan** [comment]
The shadow slightly spreads, due to the scale effect. I believe you could add an animation by subclassing the pulse view and adding animations to the touch handlers that spreads the shadow, and contracts it. I am not going to make this a priority right now, but we are planning some nice additions with 3D touch and such, and that is when this issue will be considered at a high priority.

Feel free to continue the dialog on this, though for cleanup reasons, I will close the issue.
