### ISSUE TITLE
NavigationController example?

### ISSUE THREAD

**Issue by HowardCsie** [CosmicMind/Material#270]
Is there any example that i can learn how to use it? Thanks.

**Comment by danieldahan** [comment]
Yes, check the App example. It has the NavigationController in there, which will show you how to use it effectively in a more elaborate app.

**Comment by HowardCsie** [comment]
![image](https://cloud.githubusercontent.com/assets/17197816/14152881/da8358b0-f6e7-11e5-81e5-deb336dd34fe.png)
I use storyboard to place my navigationController.
```
private func prepareNavigationBar() {
        let nav = self.navigationController as! NavigationController;
        nav.navigationBar.statusBarStyle = .LightContent
        nav.navigationBar.tintColor = MaterialColor.white
        nav.navigationBar.backgroundColor = MaterialColor.blue.base
        nav.navigationItem.titleLabel = titleLabel
        nav.navigationItem.leftControls = [menuButton]
        nav.navigationItem.rightControls = [switchControl]
    }

```
However,it did not work.

**Comment by danieldahan** [comment]
I see. What was the error?

**Comment by HowardCsie** [comment]
![image](https://cloud.githubusercontent.com/assets/17197816/14152976/68d4a466-f6e8-11e5-8bab-5782037dcb7b.png)
Nothing changed:((

**Comment by danieldahan** [comment]
This is because in order to use the NavigationBar, which is the subclass of UINavigationBar in the Material NavigationController class, the initialize that needs to be used is the initializer with the rootViewController property. I don't think Storyboards would be calling that initializer. Let me see if I can make it work :)

**Comment by HowardCsie** [comment]
Thank you in advance.Look forward to your solution:)

**Comment by danieldahan** [comment]
No worries :) 

So the issue is, you need to set the UINavigationBar class to NavigationBar, in the Material module. That will fix your issue. I added an example project to Storyboards showing how to do this. 

[NavigationController Storyboard Example](https://github.com/CosmicMind/Material/tree/development/Examples/Storyboards/NavigationController)
