### ISSUE TITLE
SideNavigation hideStatusBar swallowing touches

### ISSUE THREAD

**Issue by HarrisonJackson** [CosmicMind/Material#280]
This was definitely a tough one to track down, but I was able to find an acceptable workaround so maybe low priority if it's not biting too many people. Side note: Thanks for all the hard work and opening this to the community. Do yall have some links to apps Cosmic Mind has developed?

### Actual behavior

Touches are swallowed by the side navigation - content views with horizontal scroll or horizontal pan gestures don't capture any touches. This may extend beyond those cases; that's just what I tested.

### Expected behavior

Touches/Gestures pass through - content views with horizontal scroll or horizontal pan gestures work

### Theories

See the gif below - there's something odd in the `hideStatusBar` method

### Workaround 

```
let sideNavVC = SideNavigationController(rootViewController: rootVC, leftViewController: leftVC, rightViewController: rightVC)
sideNavVC.enableHideStatusbar = false
```

![touch_bug](https://cloud.githubusercontent.com/assets/1638561/14224094/30b6da16-f84d-11e5-95cc-f038ad7a3cc7.gif)

**Comment by HarrisonJackson** [comment]
Appears to be this:
https://github.com/CosmicMind/Material/blob/master/Sources/SideNavigationController.swift#L875-L877

```
if false == self?.opened {
	self?.userInteractionEnabled = true
}
```

**Comment by danieldahan** [comment]
I think that the issue is the userInteractionEnabled flag is being set to false during the statusBar `hide` animation. It is not necessary to combine that functionality. I removed it in [1.38.5](https://github.com/CosmicMind/Material/releases/tag/1.38.5). Please reopen or create a new issue if this persists. 

As for apps by CosmicMind, we are working on one to release :)
