### ISSUE TITLE
Dismiss after Transition not working

### ISSUE THREAD

**Issue by GreyEcologist** [CosmicMind/Material#286]
Hey, from my masterViewController I transition to detailViewController:

```
        self.sideNavigationController?.transitionFromRootViewController(detailVC,
                                                                        duration: 0.5,
                                                                        options: UIViewAnimationOptions.CurveEaseInOut,
                                                                        animations: nil,
                                                                        completion: nil)
```

But from the detailViewController I can't dismiss it back to masterViewController:
```
    func backAction() {
            //self.sideNavigationController!.dismissViewControllerAnimated(true, completion: nil)
            self.dismissViewControllerAnimated(true, completion: nil)
    }
```
I tried either of the two calls, neither work. Both of the viewcontrollers are SideNavigationControllerDelegate. Not sure what I'm missing.

**Comment by danieldahan** [comment]
The SideNavigationController doesn't present a ViewController, it transitions the rootViewController. This means that rather than adding a new ViewController to the view hierarchy, it swaps one out for another. So the dismiss method wouldn't work as it doesn't have a ViewController available. 

You have two options... 

1. Transition back to the original ViewController, using the same approach with ```transitionFromRootViewController```. 
2. Preset the ViewController with normal methods available on a UIViewController, and then the dismiss will work accordingly. 

If you need any further help, we are here :)
