### ISSUE TITLE
Default iOS Clear Button on TextField

### ISSUE THREAD

**Issue by MPiccinato** [CosmicMind/Material#306]
I cannot seem to get the default Clear button to display on the TextField. Any ideas how to go about this?

**Comment by danieldahan** [comment]
So this was an interesting issue. The clearButton uses the clearButton property, obviously. The KVO value internally is _clearButton which actually creates an issue, since the original clearButton is no longer accessible. So the best solution, without causing weird naming, would be to update the image of the clearButton and remove the pulse animation. 

I am not in favor of changing the name of the clearButton as it will lose its intuitive nature. If you have any suggestions or further questions, please feel free to reopen or create a new issue.

**Comment by MPiccinato** [comment]
I think it would be a reasonable approach to mimic the native clearButton. I'll give it a go, thanks!

**Comment by danieldahan** [comment]
Well by mimic, do you mean make it exactly what it is? We can discuss it prior to any effort being made? The idea of the clearButton is to create the appearance of Material Design, since the component is fully geared that way. If all it takes is an image update and no one is the wiser, what would extra logic add?

Mainly I want to understand the thinking here so we can come to the best solution.

**Comment by MPiccinato** [comment]
Sorry if I wasn't clear. I am going to use an image, similar to the native clear button, and disable the pulse animation. No extra logic, just setting the props when setting up the control.

We really liked the floating label concept from Material and wanted to apply it to our forms but still keep the native feel when it came to buttons, such as the default clearButton.

**Comment by danieldahan** [comment]
Ah... Cool. We are planning on launching a really cool feature based on Theming which will essentially allow combinations and consistency with each platform. So much ahead and I appreciate your help in making things awesome. I will close this for now.
