### ISSUE TITLE
Cardview Issue when enabling pulseScale

### ISSUE THREAD

**Issue by HowardCsie** [CosmicMind/Material#310]
I used Cardview to design my login pop-up window ,and i added the RaisedButton to my detailView of Cardview.It looks fine below.
![img_5658](https://cloud.githubusercontent.com/assets/17197816/14550566/4fa44648-02fc-11e6-9418-1851ef5ff71c.jpg)

However , i got the blurry button after triggering the pulseScale effect.
Is this a bug?Thanks.
![img_5659](https://cloud.githubusercontent.com/assets/17197816/14550567/51db3c46-02fc-11e6-8318-b5e9f6d1da69.jpg)
By the way, how can i get the height of Cardview?I always get 0.0 as a result.
`print(cardView.height)`

**Comment by danieldahan** [comment]
Hey, This could be an effect of rasterization... can you share more about your setup? Also, if you want the height of the CardView and you are using AutoLayout, you should call `layoutIfNeeded` and then the height should be available to you.

**Comment by danieldahan** [comment]
Hi @HowardCsie I haven't heard from you, so I am going to assume your issue is resolved. One reason you may get the blurry effect is because you are using non-integral values for the button. If you are using AutoLayout, this could be because of a different issue. When you have the time, please show me the code you are using to create this and then I can help you further. Thank you!

**Comment by HowardCsie** [comment]
`func xibSetup() {
        let view = NSBundle.mainBundle().loadNibNamed("loginView", owner: self, options: nil).first as! UIView
        view.frame = self.bounds
        view.backgroundColor = UIColor(red: 23/255, green: 181/255, blue: 218/255, alpha: 1)
        
        accountTF.placeholder = "單一入口帳號"
        accountTF.placeholderTextColor = UIColor(red: 1, green: 1, blue: 1, alpha: 0.8)
        accountTF.lineLayerActiveColor = UIColor(red: 1, green: 1, blue: 1, alpha: 1)
        accountTF.lineLayerColor = UIColor(red: 1, green: 1, blue: 1, alpha: 0.8)
        accountTF.font = RobotoFont.regularWithSize(17)
        accountTF.textColor = MaterialColor.white
        accountTF.titleLabel!.font = RobotoFont.mediumWithSize(14)
        accountTF.titleLabelColor = MaterialColor.white
        accountTF.titleLabelActiveColor = MaterialColor.white
        accountTF.clearButtonMode = .UnlessEditing
        accountTF.backgroundColor = MaterialColor.clear
        accountTF.delegate = self
        
        passwdTF.placeholder = "密碼"
        passwdTF.placeholderTextColor = UIColor(red: 1, green: 1, blue: 1, alpha: 0.8)
        passwdTF.lineLayerColor = UIColor(red: 1, green: 1, blue: 1, alpha: 0.8)
        passwdTF.lineLayerActiveColor = UIColor(red: 1, green: 1, blue: 1, alpha: 1)
        passwdTF.font = RobotoFont.regularWithSize(17)
        passwdTF.textColor = MaterialColor.white
        passwdTF.titleLabel!.font = RobotoFont.mediumWithSize(14)
        passwdTF.titleLabelColor = MaterialColor.white
        passwdTF.titleLabelActiveColor = MaterialColor.white
        passwdTF.clearButtonMode = .Never
        passwdTF.backgroundColor = MaterialColor.clear
        passwdTF.detailLabel = UILabel()
        passwdTF.detailLabel!.text = "您所輸入的帳號和密碼不相符"
        passwdTF.detailLabel!.font = RobotoFont.mediumWithSize(12)
        passwdTF.detailLabelActiveColor = MaterialColor.red.accent3
        passwdTF.delegate = self
        passwdTF.returnKeyType = UIReturnKeyType.Done
        
        submitButton.setTitle("Go", forState: .Normal)
       
        submitButton.titleLabel!.font = RobotoFont.mediumWithSize(16)
        submitButton.shadowColor = MaterialColor.clear
        submitButton.titleLabel!.shadowColor = MaterialColor.clear
        submitButton.backgroundColor = UIColor(red: 81/255, green: 127/255, blue: 164/255, alpha: 1)//按鈕顏色    
        addSubview(view)
    }`
This is my current setting.I use xib to implement my detailview.I also use auto layout dealing with my button.

**Comment by danieldahan** [comment]
Where is your code being loaded? Is this in a UIView or UIViewController? I noticed that you are using a property called `view`, which would not be good in a UIViewController, since it may conflict with the UIViewController `view` property. Other than that, your code looks fine. This leads me to believe it is in your Storyboards layout. What is the layout configuration of your button, cardview, and field?

**Comment by HowardCsie** [comment]
This is being loaded by ```UIview```
Here is the init.
```
class loginView: UIView{
    override init(frame: CGRect) {
            super.init(frame: frame)
            xibSetup()
     }
}
```
Here is the button autolayout.
<img width="677" alt="2016-04-21 11 09 00" src="https://cloud.githubusercontent.com/assets/17197816/14696877/7977d61a-07b1-11e6-9888-913f4bfd62b2.png">

**Comment by danieldahan** [comment]
I still don't see any issue. If you can send a sample project with this to support@cosmicmind.io, I will work on fixing it.

**Comment by HowardCsie** [comment]
I sent it:))

**Comment by danieldahan** [comment]
@HowardCsie So in your loginView, you need to set the `contentScaleFactor`.

```swift
submitButton.contentScaleFactor = MaterialDevice.scale
```

Also, if you do not want the shadow to be displayed, set the `depth` to .None, rather than setting the `shadowColor` to MaterialColor.clear.

```swift
submitButton.depth = .None
```

And that should fix your issue. If the issue persists, please reopen or create a new issue :)

**Comment by HowardCsie** [comment]
Thanks.It works.
