### ISSUE TITLE
Please make public leftViewWidth/rightViewWidth of SideNavigationController

### ISSUE THREAD

**Issue by hvbnet** [CosmicMind/Material#321]
Please make public leftViewWidth/rightViewWidth of SideNavigationController if possible.

Thanks

**Comment by danieldahan** [comment]
You can set the `leftViewWidth` and `rightViewWidth` through the `setLeftView` and `setRightView` functions. The reason for this, is because of the management of internal values that follow. If you need further help, please reopen or create a new issue. Also, if you can suggest why you need those to be public setters, that would be great.
