### ISSUE TITLE
How to add MKMapView into a CardView's Detail View Programmatically 

### ISSUE THREAD

**Issue by psuedonovicecoder** [CosmicMind/Material#350]
`let mapView:MKMapView = MKMapView()
 mapView.mapType = .Standard       
mapView.frame = view.frame
 mapView.delegate = self
view.addSubview(cardView)
cardView.detailView = mapView
cardView.translatesAutoresizingMaskIntoConstraints = false
MaterialLayout.alignFromTop(view, child: cardView, top: 200)
MaterialLayout.alignToParentHorizontally(view, child: cardView, left: 20, right: 20)`

 This code seems to result in a blank CardView with just the header and bottom buttons.
Sorry, I couldn't space the code out.

**Comment by mohpor** [comment]
I ran a test with the code excerpt you've provided and found that you are right about it. It seems that constraints cannot be made for map view (or because of the very complex internal layout system, layout cannot determine the size.). In anyway, if you use a top + bottom constraint for your card view, you'll be able to have your map view inside a card view:
e.g.: 

```
//    MaterialLayout.alignFromTop(view, child: cardView, top: 200, )
    MaterialLayout.alignToParentVertically(view,child: cardView, top: 200, bottom: 200)
```

P.S.: use triple back-tick to insert a block of code or simple use the code block sign on the rich text editor on top of your input field to format your selected text as code block.

**Comment by danieldahan** [comment]
Yes, the issue is that you were not setting the Vertical alignment. If you have any further issues, please reopen or create a new issue. 

Thank you! and @mohpor Thanks for the answer.
