### ISSUE TITLE
ScrollView within CardView's detailView

### ISSUE THREAD

**Issue by jongarate** [CosmicMind/Material#368]
Hello everyone,

I've been banging my head against the wall for a couple of days now trying to include a _UIScrollView_ with scalable text content in the _detailView_ of a **CardView** element. I've based my closest attempts in the code @mohpor provided on issue #364 but It seems I can't pin down the problem.

This is the code currently firing up on _viewDidLoad()_. **cardView** is linked with the Storyboard and both **cardTitle** and **cardBody** are _NSString_ elements coming from the Segue that launched the View.

```
cardView.divider = false
cardView.backgroundColor = MaterialColor.white
cardView.image = UIImage(named: "Material-iTunesArtWork")?.resize(toHeight: 75)
cardView.contentsGravityPreset = .BottomRight

// Title label.
let titleLabel: UILabel = UILabel()
titleLabel.text = cardTitle as String
titleLabel.textColor = MaterialColor.black
titleLabel.font = RobotoFont.mediumWithSize(24)

cardView.titleLabel = titleLabel

// Detail label.
let detailView = MaterialView(frame: CGRect(x: 0, y: 0, width: 150, height: 200))
let scrollView = UIScrollView(frame: CGRect(x: 0, y: 0, width: 150, height: 200))
let detailLabel: UILabel = UILabel()
detailLabel.text = cardBody as String
detailLabel.textColor = MaterialColor.black
detailLabel.numberOfLines = 0
detailLabel.autoresizingMask = [.FlexibleWidth, .FlexibleHeight]
detailLabel.sizeToFit()
scrollView.addSubview(detailLabel)
scrollView.autoresizesSubviews = true
scrollView.autoresizingMask = [.FlexibleWidth, .FlexibleHeight]
detailView.addSubview(scrollView)
detailView.autoresizesSubviews = true
detailView.grid.axis.direction = .Vertical
detailView.grid.rows = 1
detailView.grid.columns = 1
detailView.grid.views = [detailLabel]        

cardView.detailView = detailView

// Share button.
let img1: UIImage? = MaterialIcon.cm.check
let btn1: IconButton = IconButton()
btn1.pulseColor = UIColor.grayColor()
btn1.tintColor = MaterialColor.black
btn1.setImage(img1, forState: .Normal)
btn1.setImage(img1, forState: .Highlighted)

// Add buttons to left side.
cardView.rightButtons = [btn1]

cardView.translatesAutoresizingMaskIntoConstraints = false
self.view.addSubview(cardView)
MaterialLayout.alignToParentHorizontally(self.view, child: cardView)
MaterialLayout.alignToParentVertically(self.view, child: cardView)
```

Symptons are that the text inside _UILabel_ get truncated and there's no scroll.

Thank you for your time.

**Comment by mohpor** [comment]
@jongarate 
There are a few things that come to mind after reading your code:

1. if you are going to explicitly size the `detailView` and the `scrollView`, you probably can ignore the `Grid` part of the `detailView`. There is nothing particularly wrong with grid in this case, it's just not necessary anymore. 
2. Dynamic height `UILabel`s need to be played out more carefully. If I had to do it myself, I would probably use a `UITextView` instead, and disable the edit functionality of it. TextViews handle multi line texts with their internal scroll view and therefor that `scrollView` becomes redundant.
3. `sizeToFit()` needs to be called very carefully and almost after adding to view hierarchy so that layout system have some clue on how to decide on width and height of the text. When in doubt, calculate a text's bounds using functions like `sizeThatFits()` or other similar methods on String and `NSAttributedString`, or, alternatively, you could set `preferredMaxLayoutWidth` as a hint to layout system to calculate the text's size.
4. You should set `contentSize` on scroll view to let it know how much areas it should cover. all you're doing is to set the frame size of the scroll view. frame is the area is visible on view, but content size is the area it holds inside.
5. For further reading on sizing your `UILabel` follow this [thread](http://stackoverflow.com/questions/7174007/how-to-calculate-uilabel-height-dynamically) or similar ones.

I hope it helps. Let me know if you needed more assistance.
M.

**Comment by jongarate** [comment]
You are right in that `UITextView` made things a whole lot simpler, removing the need for `ScrollViews`, `Grids`, etc...

However, I had severe difficulties making the size of the card dynamic for certain sizes of the content within the `UITextView` and hence, I achieved a simpler solution by using native `UIKit` items.

Again, thank for your time and keep up the good work with this library. I shall now close this issue.
