### ISSUE TITLE
Can't set detailLabel.text in Toolbar.

### ISSUE THREAD

**Issue by TheHmmka** [CosmicMind/Material#393]
Hello again! :-)

Strange behavior with setting text for detailLabel in Toolbar.

When I didn't set text for some value (or empty string @"") like `self.navigationBarView.detailLabel.text = @"";` in `-(void) viewDidLoad` method I can't set it later, for example after updating some data.

I think you need to use KVO to update properties for inners controls like UILabel or something else.

**Comment by danieldahan** [comment]
Hey! Yes you are correct. KVO needs to be added. For now, you can use `layoutSubviews()` after you update the text. We are still working on the Toolbar, so the next iteration should have a solution for this. Let me know if the issue persists, otherwise I will close this for now, and push a release shortly.
