### ISSUE TITLE
how to hide BottomNavigationController 

### ISSUE THREAD

**Issue by Elqul** [CosmicMind/Material#421]
hello,

how can i hide BottomNavigationController when i enter a new ViewController ?

**Comment by danieldahan** [comment]
@mohpor I think you helped someone else with this recently, do you want to share a solution, or I can help out :)

**Comment by mohpor** [comment]
@danieldahan will post a solution here soon.

**Comment by Elqul** [comment]
and tabBarItem.badgeValue doesnt work either with BottomNavigationController . how to fix this ? @danieldahan

**Comment by danieldahan** [comment]
@Elqul Hi, we have solved the problem and will make a release tomorrow, 1.42.0, with an example project.

**Comment by Elqul** [comment]
a day later and still no updates :(

**Comment by danieldahan** [comment]
Sorry about that. We discovered an issue with iOS, where the statusBar moves the entire NavigationBar up 20px. We didn't want to release until it was solved. So today we are working on it. Basically, your issue was because the NavigationController could not be detected by the window edges. This stopped the TabBar from being hidden. So it is all related in an interesting way.

**Comment by mohpor** [comment]
@Elqul the imminent release will solve your problem :)
Thanks for your Patience.

**Comment by danieldahan** [comment]
Hi, sorry for the delay, please try [1.42.0](https://github.com/CosmicMind/Material/releases/tag/1.42.0) for a fix. If the issue persists, please reopen or create a new issue. Thank you!

**Comment by HowardCsie** [comment]
Is there any solution? :)

**Comment by danieldahan** [comment]
Have you tried the latest release in `master` ?

**Comment by HowardCsie** [comment]
Solved. ```self.hidesBottomBarWhenPushed = true```  :))Thanks

**Comment by danieldahan** [comment]
@HowardCsie exactly :)
