### ISSUE TITLE
weird animation of navigation bar when transitioning rootviewcontroller of drawer controller 

### ISSUE THREAD

**Issue by levuhai** [CosmicMind/Material#446]
Can you please check this weird animation when transitioning rootviewcontroller of drawer controller by using the following code? Navigationbar of the replacing controller slide down over the previous controller.

if let v: NavigationController = navigationDrawerController?.rootViewController as? NavigationController {
            switch item.text  {
            case "Orange":
            **navigationDrawerController?.transitionFromRootViewController(NavigationController( rootViewController: OrangeViewController()))**
            case "Purple":
                v.pushViewController(PurpleViewController(), animated: true)
            case "Green":
                v.pushViewController(GreenViewController(), animated: true)
            case "Blue":
                v.pushViewController(BlueViewController(), animated: true)
            default:break
            }
        }

**Comment by danieldahan** [comment]
Yeah, I looked into this. It is weird. It has to do with the animation in the transition. You could avoid it in two ways. 

1. Set the transition animation to duration 0. 
2. Use a ToolbarController. 

I will look into this further, generally, it is due to the animation of the frame size change in the NavigationBar. 

To better discuss this issue if you like, use [Gitter](https://gitter.im/CosmicMind/Material) it is less noisy for watchers. 

All the best :)

**Comment by nexelen** [comment]
@danieldahan are You look this problem? I have the same problem =( . Your framework look pretty good. 
![out](https://cloud.githubusercontent.com/assets/2895753/22026278/61285552-dce1-11e6-9b79-5ae3301d631f.gif)

**Comment by danieldahan** [comment]
@nexelen this shouldn't be happening. What version of Material are you using?

**Comment by nexelen** [comment]
@danieldahan Last version

**Comment by danieldahan** [comment]
Can you send me a sample of this, because that should not be an issue. Thank you! Please send to support@cosmicmind.com :)

**Comment by nexelen** [comment]
@danieldahan ok) its done

**Comment by danieldahan** [comment]
Got it, taking a look.

**Comment by nexelen** [comment]
@danieldahan Hello! What's new? What can i do? =)

**Comment by danieldahan** [comment]
@nexelen  Hey! I haven't fully figured out your issue. May I ask, do you need the `UINavigationController` functionality, or look? Also, the issue seems to come from a miscalculation of the statusBar size because it is not visible when the `NavigationDrawerController` is opened. I am going to reopen this issue and work on it more today.

**Comment by nexelen** [comment]
@danieldahan Yes, I need the UINavigationController functionality. Thanks for the answer!

**Comment by danieldahan** [comment]
@nexelen Okay, I will work more on this today :)

**Comment by pandaxbacon** [comment]
@nexelen I have the same issue. I think the quick fix for you is to "Set the transition animation to duration 0." like @danieldahan suggested.


`(self.navigationDrawerController?.rootViewController as? AppMenuController)?.transition(to: paymentNavigationController, duration: 0, options: .beginFromCurrentState, animations: nil, completion: nil)`

**Comment by nexelen** [comment]
@pandaxbacon Thx. But for me quick fix: 
`guard let root = source.navigationDrawerController?.rootViewController as? UINavigationController else {
            fatalError("RootViewController not UINavigationController")
        }
        root.setViewControllers([destination], animated: false)
        source.navigationDrawerController?.closeLeftView()`

**Comment by danieldahan** [comment]
Not sure where you are with this. I haven't been able to reproduce this. If the issue persists, please reopen this issue. Thank you!
