### ISSUE TITLE
Benefits of NavigationController over UINavigationController

### ISSUE THREAD

**Issue by Vortec4800** [CosmicMind/Material#550]
Forgive me if I'm just missing something, but what would be the benefit of using Material's NavigationController over using the standard UINavigationController with a customer nav bar subclass (if you want to use the Material nav bar)?

**Comment by danieldahan** [comment]
No worries. It's much easier to customize, space, and manipulate. The entire library is not based on the NavBar, it's one of many components. That said, there are large and small benefits using any of the components.

**Comment by Vortec4800** [comment]
Perhaps my disconnect is that I'm not aware of the benefits of using some of these full components over just some of the UI items on top of the original frameworks. I would love a bit more detail in the already excellent readme file which seems to focus on just the UI items.

Anyway thanks for the reply!

**Comment by danieldahan** [comment]
You are 100% correct. I have been spending so much time getting CosmicMind's frameworks out there code wise, and we are shifting our efforts to documentation. I believe that everyone would benefit from really understanding the benefits and all the features. I don't imagine anyone is really using more than a small percentage of the actual features. 

I really appreciate this issue, because you are solidifying my understanding of what the community needs. I have two more days of coding before all my attention is on documentation. At that point the code is really stable, and its time to really teach how to use the libraries.

**Comment by Vortec4800** [comment]
That sounds really awesome. So far I'm basically only using a couple things like the buttons and the text fields, but it seems like there is a ton more functionality that I'm just plain unaware of.

**Comment by danieldahan** [comment]
The overall real benefit that no one is seeing is the ease in a decoupled architecture for the entire UI, as well as, the ability to build additional components from the core library. In the next couple weeks we will be all about docs and examples.
