### ISSUE TITLE
NavigationController back button not hiding

### ISSUE THREAD

**Issue by peersocialdeal** [CosmicMind/Material#561]
Hi :)

First of all, I really love this kit! <3

So, I'm developing an app right now. But I can't seem to figure out how I can hide the "default" back button on the navigation bar.

My setup (everything programmatically):

NavigationController -> ViewController
-> push
(NavigationController) -> NavigationDrawerController -> XLPagerTabStrip* -> ViewControllers

I removed the styling so I could start from scratch. It didn't help.

In my NavigationDrawerController viewDidAppear: 
(tried them all)
navigationItem.leftItemsSupplementBackButton = true
navigationItem.hidesBackButton = true

navigationItem.setHidesBackButton(true, ... )

Screenshot (ViewController): http://sup.urb.li/2iMm
Screenshot (ViewControllers + XLPagerTabStrip + DrawerController): http://sup.urb.li/18b5g

*
https://github.com/xmartlabs/XLPagerTabStrip

PS: I'm not sure this is an issue, but it's my issue.

Help is appreciated :)

Thanks

**Comment by danieldahan** [comment]
@peersocialdeal I love this line "PS: I'm not sure this is an issue, but it's my issue."

I think your setup is a bit off. You don't need to manually hide the back button. That is all done within the framework. In your `AppDelegate` you should have a setup like this: 

```swift
window!.rootViewController = NavigationDrawerController(rootViewController: NavigationController(rootViewController: PageTabBarController(viewController: [VC1, VC2, ...])))
```

The other thing to note, is if you are looking to use the `NavigationController` because you want the look and feel, but not necessarily the actual navigation benefits, I would opt in to use the `ToolbarController` instead. It will give you the same look and feel, but is more simple in its usage. 

To access the `Material` back button, in the page you want to access it, you should be able to do this

```swift
navigationItem.backButton.isHidden = true
```

After writing all this, I think this would be a great example, so I am going to make one with this setup. It will be out later today. 

And thank you very much for your support, we love working on Material :) 

I will leave this issue up as a request for a sample.

**Comment by peersocialdeal** [comment]
Awesome fast response ! 👍 

Yea, I figured my setup is that well. 

I'm kinda new to iOs dev, so this is my first "real" project. So still figuring out some things.

The way the drawer works now is to "replace" the page on the drawer root.
But the way I'm supposed to make it work is leaving the drawer to a new history item in the navigation history stack.

screenshot: http://sup.urb.li/1avf5 

top drawing is how I'm supposed to make it.
bottom drawing is how the drawer is working now, and supposed too work.


btw: iOS/NavigationBar.swift -> 303, 304
item.hidesBackButton = false
item.setHidesBackButton(true, animated: false)

Is this done so it animates? 
And if I'm correct it's hidden on default?

Thanks

**Comment by danieldahan** [comment]
Let's close this issue and move it to [Gitter](https://gitter.im/CosmicMind/Material) so we can chat more freely on how to approach setting up your app architecture. Ping me there when you are ready.

**Comment by danieldahan** [comment]
Hey, I started a samples project repository where I will make samples based on requests and needs. Here is your issue https://github.com/CosmicMind/Samples/issues/1 :) We can chat there.

**Comment by phlippieb** [comment]
Was this solved? I couldn't figure out how to do this from the sample issue.

**Comment by danieldahan** [comment]
@phlippieb Yes, take a look here https://github.com/CosmicMind/Samples/issues/1, and look at this sample [CardTableView](https://github.com/CosmicMind/Samples/tree/master/Graph/CardTableView).
