### ISSUE TITLE
navigation item problems

### ISSUE THREAD

**Issue by aemgtz** [CosmicMind/Material#587]
![screen shot 2559-11-07 at 5 30 19 pm](https://cloud.githubusercontent.com/assets/276439/20056136/416ba8ec-a517-11e6-8990-809a9fead874.png)

I have added items into leftView and rightView
Seeing my items in rightview is stay over the screen!

`navigationItem.leftViews = [menuButton,dateButton]`
`navigationItem.rightViews = [nowButton, settingsButton]`

**Comment by danieldahan** [comment]
I think that you have either one of two issues, the button is too large, or you need to set the contentViewAlignment property to .any so that it doesn’t try and center the contentView and create a funny alignment.

**Comment by aemgtz** [comment]
What do you mean by "set the contentViewAlignment" to which view?
Is it possible to set my date button as the center and adjust the inset to the left like in the screenshot?

**Comment by danieldahan** [comment]
Try the 'centerViews' property for the button. Sorry on the road, I could answer in more detail tomorrow.

**Comment by aemgtz** [comment]
Many thanks

**Comment by danieldahan** [comment]
@aemgtz Have you had a chance to try the `centerViews` property?

Some insight on the NavigationBar with NavigationItem. 

The NavigationBar is made from 3 main areas, the leftViews, contentView (centerViews), and rightViews. When you start to add items to either of the view areas, from the left to the right, it calculates the positioning of the items based on the `contentEdgeInsets`, `interimSpace`, and UIViews being positioned themselves. 

That said, there are scenarios when you would like to center the items in the contentView, which is in the middle of the leftViews and rightViews, and in order to do that, the contentView needs to make adjustments to compensate for the difference in views on either left or right side. This is where you could use the centerViews property to tell the contentView that you want things centered there. As well, you can specify to ignore the additional compensation by setting the `contentViewAlignment` property to `.any` from `.center`.  

In your case, it sounds like you want the calendar button to be in the center, which will be best done using the `centerViews` property. 

There is more detail to all this, and I think it would be best to post this knowledge on CosmicMind.com/material where everyone can learn. 

So I will do that. If you have any other issues, please reopen or create a new issue, or chat on Gitter where we can get into more details. 

Thank you :)
