### ISSUE TITLE
Unsatisfiable layout constraints in version 2.4.0

### ISSUE THREAD

**Issue by elropero** [CosmicMind/Material#634]
First, I just want to say this is a great project, thanks for all your hard work! 

With version 2.4.0, I just started noticing a bunch of "unsatisfiable layout constraints" log warnings  that did not occur in release 2.3.22.

These warnings are the result of me creating a `TableViewCell` and then calling e.g. `cell.layout(someChild).right(20)` within `tableView:cellForRowAt`, and I've confirmed that they do not happen in build 2.3.22. 

>
>     "<NSLayoutConstraint:0x60800028ba90 UITableViewLabel:0x7fa2dde3c2b0'The sky is crying'.right == Material.TableViewCell:0x7fa2dc231000'Material.TableViewCell'.right - 10   (active)>",
>     "<NSLayoutConstraint:0x600000289330 'UIView-Encapsulated-Layout-Width' Material.TableViewCell:0x7fa2dc231000'Material.TableViewCell'.width == 0   (active)>"
>

To repro, in `tableView:cellForRowAt` do:
```
let cell: Material.TableViewCell = Material.TableViewCell(style: .default, reuseIdentifier: "Material.TableViewCell")
       
let nameLabel = UILabel()
nameLabel.text = "the sky is crying"

cell.layout(nameLabel).top(20).left(10).right(80)
return cell
```

This is a simplified example, and if it's not immediately reproducible I'll create a sample project demonstrating the error. I assume it will be, since I pulled version 2.3.22 and the warnings went away.

**Comment by danieldahan** [comment]
Hey, Thank you :) It is a pleasure to work on Material with a wonderful community.

For your issue, yes please provide a sample. The warnings appearing are not necessarily a bad thing. They could have surfaced from improvements to the `Layout` class that I had recently added, which now reveal an issue in the `TableViewCell` layout code. One issue, I am thinking may be the cause is that the `TableViewCell.width` may have a value of `0`, and the constraint is failing. Either way, a sample will help.

**Comment by danieldahan** [comment]
Hey, I haven't heard from you. If you still have this issue, please reopen it or create a new one. All the best :)

**Comment by elropero** [comment]
Sorry have been traveling. Will take a look as soon as I can.

**Comment by danieldahan** [comment]
No worries :)
