### ISSUE TITLE
Delegate when using Navigation Controller and toggle right option

### ISSUE THREAD

**Issue by winniepooh001** [CosmicMind/Material#647]
Hi,

Thank you for the wonderful library. I am very new at Swift and I'm not sure if I'm not thinking in the right frame. I want to use the right view controller (FilterControl) of the navigation drawer controller as a filter such that when user is done selection the filtered items are passed back to the previous view controller (Data View). However, I'm not sure how to access the right view controller to set its delegate to (Data View) . The delegate method is working, in that if I instantiate a new Filter Control and use push when the Filter control is closed the information is passed back. However if I do toggle right, nothing will happen with delegate.

Thank you and happy holidays

**Comment by danieldahan** [comment]
Hey :) Thank you, I love working on Material with our community. As for your question, are you aware of the delegation methods for the `NavigationDrawerControllerDelegate` ? I think what you are looking for is to be notified when events occur with the `rightView` ? Is this correct?

**Comment by winniepooh001** [comment]
Hi, 
Thank you for the quick response. I'm looking for a way to have my (Data View) page adopt the delegate for my (filter page) which is set in app delgate file as the right view of navigationdrawercontroller. I'm wandering if there is a way to directly access the right view, something like let filterview = navigationdrawercontroller.rightview?

**Comment by danieldahan** [comment]
The `rightView` is a container for the `rightViewController`. In any sub view controller of the `NavigationDrawerController`, you can access the `NavigationDrawerController` using the optional helper properties. So in your `viewWillAppear` or some other process other than `viewDidLoad`, you can do this:

```swift
(navigationDrawerController?.rightViewController as? FilterViewController)?.delegate = self
```

The reason you do not want to put this in your `viewDidLoad` is because when you construct the view controller, it will call the `viewDidLoad` method, but you would have not attached it yet to the `NavigationDrawerController`, which would result in a `nil` value for the optional `navigationDrawerController` property. 

Give this a try :) Should get you in the right direction. If all is well, please close the issue, and let me know what you did.

**Comment by winniepooh001** [comment]
Thank you very much. It is working.
