### ISSUE TITLE
Dynamic height for Snackbar

### ISSUE THREAD

**Issue by Arkezis** [CosmicMind/Material#666]
Hello,

Is it possible to make the height of the Snackbar dynamic depending on the text contained ? 
I'm using it to display error messages. Sometimes, there is 2 or 3 lines of errors. Sometimes, only one ;)

Maybe a maxHeight is also relevant ? 

Thanks a lot :)

**Comment by danieldahan** [comment]
Hey, there is a way to adjust the height, using the `height` property, or `heightPreset` property. Both will adjust the size of the `Snackbar` text area since that is dependant on height. Also, there is a function `UIFont.stringSize...` that will calculate the CGSize of a string based on a given width and string value that uses a given UIFont. 

Give that a try, and let me know if you need any further help :) Reopen or create a new issue if you need. All the best!
