### ISSUE TITLE
Animating menu button in openMenu() causes menu to close

### ISSUE THREAD

**Issue by Sufi-Al-Hussaini** [CosmicMind/Material#674]
I find that adding a rotation animation to the first button in a menu in `openMenu()/closeMenu()` makes the menu close soon after it opens. The same code was working fine in 2.2.5.
```
open override func openMenu(completion: ((UIView) -> Void)? = nil) {
    super.openMenu(completion: completion)
    menu.views.first?.animate(animation: Motion.rotate(angle: 90))
}

open override func closeMenu(completion: ((UIView) -> Void)? = nil) {
    super.closeMenu(completion: completion)
    menu.views.first?.animate(animation: Motion.rotate(angle: 0))
}
```

Do I need to change something?

**Comment by danieldahan** [comment]
Hey, I am working on a release that will bring a new and more robust menu, `FABMenu`, to Material. Once I do that, I will give it to you to test and confirm the issue is fixed. Here is an article, [Transitions With FABMenuController](http://cosmicmind.sandbox.local/danieldahan/transitions-with-fabmenucontroller) that you can read in preparation on using the new `FABMenu`.

**Comment by Sufi-Al-Hussaini** [comment]
Thanks @danieldahan!

**Comment by danieldahan** [comment]
Oops... I put my local dev machine address. Here is the correct one [Transitions With FABMenuController](http://www.cosmicmind.com/danieldahan/transitions-with-fabmenucontroller).

**Comment by danieldahan** [comment]
The latest release of [Material 2.5.0](https://github.com/CosmicMind/Material/releases/tag/2.5.0) is out. Thank you!
