### ISSUE TITLE
FABMenu delegate methods not executing when manually opening/closing menu

### ISSUE THREAD

**Issue by codemodouk** [CosmicMind/Material#725]
Hi,

I'm using the FABMenu functionality standalone - i.e. not as part of the FABMenuController.

I notice that if I programatically call `open` or `close`, the `willOpen`, `willClose`, `didOpen`, `didClose` delegate methods don't get called. 

I see in the FABMenuController code there is a parameter `isTriggeredByUserInteraction`, but the use of that is internal to the class. Is this intentional?

**Comment by danieldahan** [comment]
Hey, yes this is intentional. Apple says that a ui control should not fire its delegation methods when not initiated by a user. If you are programmatically executing code, you should be able to trigger the correct functionality, or add a selector and target to the `FABMenuItem.button` as needed. If you need, please reopen the issue. Thank you!
