### ISSUE TITLE
TextField calls layoutSubviews() directly.

### ISSUE THREAD

**Issue by markst** [CosmicMind/Material#731]
What's the reason for `TextField` calling `layoutSubviews()` on `becomeFirstResponder()`?

Apple advises against calling `layoutSubviews()` directly. 

> You should not call this method directly. If you want to force a layout update, call the set​Needs​Layout() method instead to do so prior to the next drawing update. If you want to update the layout of your views immediately, call the layout​If​Needed() method.

https://developer.apple.com/reference/uikit/uiview/1622482-layoutsubviews

**Comment by danieldahan** [comment]
True, but remember I am not calling `layoutSubviews` external to the class itself. Meaning, I am not doing this: `textField.layoutSubviews()`, which is not a good idea. I'll run some tests and see if there is an improvement I can make in this area :) 

Calling it in `becomeFirstResponder` is because of the change in layout that is needed if one triggers `becomeFirstResponder` when initially loading a `TextField`.  I think this was a really good investigation on your behalf, and I will look through today for improvements. Any further suggestions and questions are always welcome, thank you!

**Comment by markst** [comment]
Hey @danieldahan thanks for response. 

I believe `layoutSubviews()` should never be called regardless of being called external or internally. 

It seems there are some progress of changes to the more appropriate way of forcing layout:
https://github.com/CosmicMind/Material/blob/5e81df5a0c3448b9c811d82e57be02e57abd59f5/Sources/iOS/TextField.swift#L385

```swift
setNeedsLayout()
layoutIfNeeded()
```

**Comment by danieldahan** [comment]
Initially I made those changes and tested all the projects. It caused some issues, so there is another method to achieve your suggestion, which I will do on my flight tomorrow. Personally, I don't see an issue with calling it internally, but I don't know everything and I can make a fix from your suggestion :) Thanks for submitting this.
