### ISSUE TITLE
Help: Launch CaptureController with front camera

### ISSUE THREAD

**Issue by bayarmanlai** [CosmicMind/Material#756]
Thanks for amazing library,

I want to launch CaptureController with front camera.
I did it that way within prepare method
```
capture.changeCamera()
capture.startSession()

```
but camera loads too slow.

Do you have any solution?

**Comment by danieldahan** [comment]
Thank you :) Can you explain more about when you are launching the camera? Possibly provide a sample project, version of Material you are using, and the device you are testing on?

**Comment by bayarmanlai** [comment]
Thanks for your response,
Material - 2.6.3
Device - iPhone 5s, iPhone7

I think below codes enough to explain my problem, If it is not I will provide sample project.

CameraViewController
```
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        prepareCapture()
    }

    func prepareCapture() {
        guard let cc = captureController as? AppCaptureController else {
            return
        }
        cc.startSession(captureRequest: self.captureRequest)
    }
```
In AppCaptureController (extends from CaptureController)
```
    func startSession(captureRequest: CaptureRequest){
        switch captureRequest {
        case .selfieVideo:
            capture.mode = .video
            capture.changeCamera()
        case .selfiePhone:
            capture.mode = .photo
            capture.changeCamera()
        case .photo:
            capture.mode = .photo
        }
        capture.startSession()
    }

```
Show CameraViewController
`AppCaptureController(rootViewController: CameraViewController())`

**Comment by danieldahan** [comment]
I have been looking into it, and it looks like the camera starts out at the back because on iPhones it wasn't always guaranteed that the device would have a camera in the front. Why not start the camera in the background when the app opens? Only on the initial launch of your app would it be the slowest as you will need permission from the user to use the camera. One of my next areas of focus is to rewrite the camera component to handle its short comings and I will be adding new features. I will be able to investigate further then. If you need any further help, please reopen the issue. 

Thank you! :)
