### ISSUE TITLE
iOS 8 Freezing issues 

### ISSUE THREAD

**Issue by dk53** [CosmicMind/Material#795]
Hello,

I ran thru an issue when adding a subview to a pageTabBarItem in iOS 8.

CPU goes up to 100 % and app is frezzing.

Working perfectly when configuring a pageTabBarItem (setting it text properties, etc), but not when adding a subview to pageTabBarItem.

Issues is reproductible with latest tools at this date : Xcode 8.3.3, Swift 3 and latest Material version.

It's not reproductible on iOS 9+ 

Thanks for the support.

**Comment by dk53** [comment]
I made a github repo https://github.com/dk53/materialTabBarTest to reproduce this issue.

Tested with an iOS 8.1 simulator

**Comment by danieldahan** [comment]
Thank you! I will take a look at see what's happening.

**Comment by danieldahan** [comment]
I am not able to get that sample simulator, so I cannot reproduce your issue. As well, we would need to confirm the findings on a device. Simulators are not reliable. Can you think of an approach going forward to test this? The CPU hitting 100% and freezing the app sounds really weird for that behavior, especially since you are using all of Apple's APIs. Adding a view to a PageTabBarItem is equivalent to adding a view to a UIButton. If you can give me more to work with, I'd be happy to continue investigating. Please reopen the issue if you need :) Thank you!
