### ISSUE TITLE
Page tab bar lag issue

### ISSUE THREAD

**Issue by wlching** [CosmicMind/Material#800]
I used pageTabBarController to handle 4 viewcontrollers. One of them is a camera which is used to scan QRCode.(I guess it is the reason why it lags.)
Could I close tab bar bounce(damping) animation and keep transition effect only?
I try to set isBounceEnabled false, but it would close swipe function also.
Thanks.

**Comment by danieldahan** [comment]
This issue is combined in a few others. The PageTabBar is being replaced within a couple releases. It is already working as a prototype, but not ready for production. It will have the feature you are looking for then. The current issue is more of a limitation that is imposed by the base UIPageViewController provided by Apple. Watch the updates coming and you will have the feature really soon. Thank you!

**Comment by wlching** [comment]
Thanks a lot. :)

**Comment by wlching** [comment]
Hello @danieldahan , may I suggest an idea?
Could you offer a property which indicator the percentage of view transition.
When user starts scrolling pageview the property is 0(0%). On the other hand, when pageview is scrolled to next page, the property is 1(100%). 
With this property, developers could do something.(ex: changing layout of view, some animations of view... and so on)
Or there is a method to do this? Could you give me a hint?
Thanks

**Comment by danieldahan** [comment]
@wlching this is a great idea in general. Would you create a feature request for this idea? Then I can update you on its release. I have a release coming up, so this may be able to squeeze in there.
