### ISSUE TITLE
Card View: How do I go about placing toolbar and bottom bar on content view ?

### ISSUE THREAD

**Issue by TeplrGuy** [CosmicMind/Material#819]
Instead of having it align right at top and bottom respectively

**Comment by danieldahan** [comment]
Instead of adding the Toolbar and Bar to the Card component, add them as subviews of the contentView. Then in code you can probably do something like this: 

```swift
card = Card()
card.contentView = UIView(...)

let toolbar = Toolbar()
card.contentView?.layout(toolbar).horizontally().top()

let bar = Bar()
card.contentView?.layout(bar).horizontally().bottom()
```

Something like that. Give it a try, and if you need any further help, message me on [Material Gitter](https://gitter.im/CosmicMind/Material) :) All the best!
