### ISSUE TITLE
Viewcontroller animated weird when swiping out of Navigation Controller from edge

### ISSUE THREAD

**Issue by HowardCsie** [CosmicMind/Material#874]
As Title. Thanks:)

Material Navigation Controller
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/17197816/30772439-afa3733a-a020-11e7-9b88-3cf369f2fbc9.gif)

UINavigationController
![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/17197816/30772552-7565a1f4-a023-11e7-8190-b6bcbb794378.gif)

**Comment by danieldahan** [comment]
Very interesting, I will see if I can reproduce this. If you have a reproducible project, please share :) Thank you!

**Comment by chilinh** [comment]
This happens because of [contentInsetAdjustmentBehavior](https://developer.apple.com/documentation/uikit/uiscrollview/2902261-contentinsetadjustmentbehavior).
I guess you use UITableView for Navigation root view controller so you can add this code to viewDidLoad of that controller:
`if #available(iOS 11.0, *) {
    tableView.contentInsetAdjustmentBehavior = .never
}`

**Comment by HowardCsie** [comment]
@chilinh Thank you! It works.
