### ISSUE TITLE
Decouple SnackbarController 

### ISSUE THREAD

**Issue by GreyEcologist** [CosmicMind/Material#875]
Hey, is there way to use the SnackbarController without setting a rootViewController? I have a Navigation Stack and I use UI ViewControllers transitions, so I've haven't been able to refactor my stack and making the call below:

 rootviewcontroller = AppSnackbarController(rootViewController: RootViewController())

Is this the only way to call the SnackbarController?

**Comment by danieldahan** [comment]
The easiest method for your issue is to set the navigation stack as the root view controller. Otherwise, look at the controller logic and copy that into your view controller, or subclass the SnackbarController and then add the details into your view controller as is. Other than that, until we refactor this design pattern, there isn't another option.
