### ISSUE TITLE
addAttributes conflict with Swift 4

### ISSUE THREAD

**Issue by theolof** [CosmicMind/Material#891]
In `Material+NSMutableAttributedString.swift`:
```
open func addAttributes(_ keys: [NSAttributedStringKey: Any], range: NSRange) {
        for (k, v) in keys {
            addAttribute(k, value: v, range: range)
        }
    }
```
This conflicts with addAttributes in `Foundation.NSAttributedString.swift`:
```
open func addAttributes(_ attrs: [NSAttributedStringKey : Any] = [:], range: NSRange)
```
A workaround is to use `updateAttributes` until it's fixed.

**Comment by danieldahan** [comment]
Hmm... can you show me the error for this. I don't see it when I compile. Thank you!

**Comment by titiphoque** [comment]
I have the same issue : 

`Material.NSMutableAttributedString:7:15: note: found this candidate
    open func addAttributes(_ keys: [NSAttributedStringKey : Any], range: NSRange)
              ^
Foundation.NSMutableAttributedString:4:15: note: found this candidate
    open func addAttributes(_ attrs: [NSAttributedStringKey : Any] = [:], range: NSRange)`

Why do you have this method in your extension ? This method exists since iOS 3.2+ (see: https://developer.apple.com/documentation/foundation/nsmutableattributedstring/1414304-addattributes)

**Comment by theolof** [comment]
Compilation error:
```
/Users/...ActivityCell.swift:237:9: Ambiguous use of 'addAttributes(_:range:)'
```

**Comment by danieldahan** [comment]
I removed that function :) in this release [Material 2.10.4](https://github.com/CosmicMind/Material/releases/tag/2.10.4). Thanks for sharing.
