### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by phongyu** [CosmicMind/Material#990]
Hi,

I just updated Material to version 2.12.17, and I got errors when compiling the app

![screen shot 2017-12-01 at 11 15 23](https://user-images.githubusercontent.com/19926283/33480587-0f13a512-d689-11e7-96a5-949967dd6a1b.png)

I set Language Version for xcode: Swift 4.0 as some advices, but it doesn't help. 

Please help !

**Comment by muzoman** [comment]
These errors might occur if you don't specify the IOS platform that you're targeting in your project podfile. If you're trying to compile one of the sample Apps then make sure the samples podfile first line is uncommented and looks like: 

platform :ios, '9.0'

Then run command >pod update

Then make sure you open up the workspace Xcode file rather than project.

**Comment by hariprasadiit** [comment]
facing same problem. project compiles with `v2.9.4`.

**Comment by danieldahan** [comment]
Your project needs to be set for Swift 4, including your Pods settings if you are using CocoaPods. Al the best!

**Comment by dakamojo** [comment]
I have the same build errors.  I am building the sample project CardTableView.  Below is my podfile.  I have already updated Graph to use the development branch because I understand that is needed for Swift 4.  The build settings in both my Pods project and my CardTableView project are set to Swift 4.

```

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'CardTableView' do
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

# Pods for CardTableView
pod 'Material', '~> 2.0'
#pod 'Graph', '~> 2.0'
pod 'Graph', :git => 'https://github.com/CosmicMind/Graph.git', :branch => 'development'



end


```
